---
knit: "bookdown::render_book"
---

# Acknowledgements {-}

## Personal {-}

I wish to sincerely thank both my supervisors Dr Biggs and Dr Roberts alongside my advisor Dr Boruff for their advice, contributions and enthusiasm throughout this thesis. Specifically, Dr Biggs continuously challenged how developed methodologies were applicable in applied planning terms, complemented by Dr Roberts who would challenge more technical aspects of the research and Dr Boruff who would often question the applicability to the bigger, global picture. Combined they have been a simply fantastic supervisory team that have undoubtedly developed my overall research skills. Beyond the methodological and technical aspects of the project the team have consistently encouraged me, provided numerous further opportunities and promoted both my work and I. I am extremely grateful the time all three academics have invested in me and for how much I have learnt from them over the last four years. 
I also thank those not officially involved with this thesis but have nonetheless contributed in ways they were probably unaware of. This is especially true of all those I have cycled with, taking my mind away from research, subsequently feeling refreshed and often having methodological breakthroughs. Similarly (soon to be Drs) Luke Brown and Micheline Campbell for their friendship, advice and support through the rollercoaster of emotions during the project. I thank Amelia Vincent for her unrelenting encouragement and empathy over the last four years. Finally I wish to thank my parents, Valerie and Angus MacLachlan, for their continued encouragement and investment throughout my entire education.  

## Funding and data access {-}

This work was supported by the Economic and Social Research Council (ESRC) [grant number ES/J500161/1] and the University of Southampton School of Geography and Environmental Science, with institutional visit funding support from the University of Southampton via the World University Network (WUN) researcher mobility programme and Study Abroad department. Appreciation is shown to the University of Western Australia (UWA) and the UWA School of Agriculture and Environment for supporting grant and visa applications alongside hosting institutional visits. Access to Urban Monitor high resolution data over the Perth Metropolitan Region was provided in part through the National Environmental Science Program, Clean Air and Urban Landscapes Hub. I would like to respectively thank t the United States Geological Survey (USGS) and Goddard Space Flight Center for continuing to supply free Landsat and Moderate Resolution Imaging Spectroradiometer (MODIS) data used throughout this project. I also express gratitude to Western Australia Department of Planning (WAPC), in particular Matt Devlin and Lisl van Aarde for urban estimate data and supplementary planning information used within chapter 4. In a similar theme the City of Fremantle, especially Mayor Brad Pettitt, Paul Garbett, Marcel Maron and Gavin Giles who provided valuable localised operational planning insights used to inform analysis in chapter 7. I also extend further thanks to the ESRC, School of Geography and Environmental Science and University of Southampton for the numerous free training sessions and qualifications on offer that have enhanced my research outputs, professional development and overall doctorate experience. Finally I wish to thank my mother and late father for continuing to support my education and providing funds for research equipment and field visits. 
 
