---
knit: "bookdown::render_book"
---
# Academic Thesis: Declaration of Authorship  {-}

I, Andrew Charles MacLachlan

declare that this thesis and the work presented in it are my own and has been generated by me as the result of my own original research.

Earth Observation for Quantifying Urban Growth and its Application to Sustainable City Development

I confirm that:

1.	This work was done wholly or mainly while in candidature for a research degree at this University;

2.	Where any part of this thesis has previously been submitted for a degree or any other qualification at this University or any other institution, this has been clearly stated;

3.	Where I have consulted the published work of others, this is always clearly attributed;

4.	Where I have quoted from the work of others, the source is always given. With the exception of such quotations, this thesis is entirely my own work;

5.	I have acknowledged all main sources of help;

6.	Where the thesis is based on work done by myself jointly with others, I have made clear exactly what was done by others and what I have contributed myself;

7.	Parts of this work have been published as:

MacLachlan, A., Biggs, E., Roberts, G. and Boruff, B., 2017. Urban growth dynamics in Perth, Western Australia: using applied remote sensing for sustainable future planning. Land, 6(1), p.9. [open access].

MacLachlan, A., Biggs, E., Roberts, G. and Boruff, B., 2017. Classified Earth observation data between 1990 and 2015 for the Perth Metropolitan Region, Western Australia using the Import Vector Machine algorithm, PANGAEA, https://doi.org/10.1594/PANGAEA.871017 [data]. [open access].

MacLachlan, A., Roberts, G., Biggs, E. and Boruff, B., 2017. Subpixel land-cover classification for improved urban area estimates using Landsat. International Journal of Remote Sensing, 38(20), pp.5763-5792. [open access].

MacLachlan, A., Biggs, E., Roberts, G. and Boruff, B., 2017. Urbanisation-Induced Land Cover Temperature Dynamics for Sustainable Future Urban Heat Island Mitigation. Urban Science, 1(4), p.38. [open access].

MacLachlan, A., Biggs, E., Roberts, G. and Boruff, B., 2018. Earth Observation for Sustainable City Planning. [submitted to Global Environmental Change].

Smith, A., MacLachlan, A., Haworth, B., Biggs, E. and Maginn, P., 2018. Demonstrating the global potential of a high-resolution spatiotemporal population modelling framework. International Journal of Geographical Information Science [under review].

In all jointly published work presented in this thesis Andrew MacLachlan was responsible for sourcing data, liaising with planning authorities, devising methodological approaches, all analysis and producing and revising manuscript drafts. Dr Biggs and Dr Roberts contributed ideas, comments and data in a supervisory capacity based on their own expertise throughout the research. Dr Boruff supported the research in similar manner through an advisory role at the University of Western Australia. Author attribution statements for each individual paper are presented below, providing specific details into Andrew MacLachlan’s responsibilities and the supervisory and advisory support supplied by Dr Biggs, Dr Roberts and Dr Boruff. All authors declare no completing interests.

Author attribution statements

Chapter 4, paper 1a

Chapter 4 corresponds to the publication: 

MacLachlan, A., Biggs, E., Roberts, G. and Boruff, B., 2017. Urban growth dynamics in Perth, Western Australia: using applied remote sensing for sustainable future planning. Land, 6(1), p.1-14. 

Andrew MacLachlan liaised with and obtained data from the Western Australian Department of Planning, analysed all data and produced manuscript drafts. The co-authors assisted in guiding the overall research objectives, provided methodological advice and revised manuscript text in a supervisor capacity. In particular Dr Biggs contributed valuable figure and policy recommendations whilst Dr Roberts ensured valid data normalisation suggesting analysis found in the supplementary material, section 4.7.

Chapter 4, paper 1b

The data produced using the methodology described in Paper 1a (main body of chapter 4) corresponds to the publication: 
MacLachlan, A., Biggs, E., Roberts, G. and Boruff, B., 2017. Classified Earth observation data between 1990 and 2015 for the Perth Metropolitan Region, Western Australia using the Import Vector Machine algorithm, PANGAEA, https://doi.org/10.1594/PANGAEA.871017. 
Andrew MacLachlan produced and formatted the data for publication, with methodological advice from co-authors in a supervisory capacity. 
Chapter 5, paper 2
Chapter 5 corresponds to the publication: 
MacLachlan, A., Roberts, G., Biggs, E. and Boruff, B., 2017. Subpixel land-cover classification for improved urban area estimates using Landsat. International Journal of Remote Sensing, 38(20), pp.5763-5792. 
Andrew MacLachlan was responsible for designing the methodology, processing all data and producing manuscript drafts. Co-authors agreed upon and guided the research questions, provided access to high resolution aerial data, gave methodological and practical advice and reviewed manuscript drafts in a supervisory capacity. More specifically, Dr Boruff provided high resolution data, with Dr Roberts advising Andrew MacLachlan on the best Object Based Image classification procedures. 
Chapter 6, paper 3
Chapter 6 corresponds to the publication: 
MacLachlan, A., Biggs, E., Roberts, G. and Boruff, B., 2017. Urbanisation-Induced Land Cover Temperature Dynamics for Sustainable Future Urban Heat Island Mitigation. Urban Science, 1(4), pp.1-21. 
Andrew MacLachlan designed the methodological procedure, processed and analysed all data and produced manuscript drafts. The co-authors assisted in guiding research objectives and provided valuable advice and manuscript comments in a supervisory capacity. Dr Biggs critically commented on policy applications and data output, especially Figure 6 8 that was selected for the Journal Issue front cover. Dr Roberts provided practical methodological advice and assisted in selecting appropriate data for figures and tables presented throughout the paper.
Chapter 7, paper 4
Chapter 7 corresponds to the pending publication:
MacLachlan, A., Biggs, E., Roberts, G. and Boruff, B., 2018. Earth Observation for Sustainable City Planning [submitted to Global Environmental Change]. 
Andrew MacLachlan identified and processed all data required used within the modelling methodology, produced figures, liaised with the City of Fremantle and drafted all versions of the manuscript. Co-authors guided the overall objectives ensuring linkage to previous work whilst also providing critical feedback in a supervisory capacity. Dr Biggs ensured policy relevance and critically commented on produced figures. Dr Roberts contributed ideas throughout and reviewed the final draft manuscript alongside Dr Boruff. 
Signed:	[signature removed from digital version]
Date:	14/09/2018
Andrew MacLachlan
As a supervisor for this postgraduate student I certify that the authorship attribution statements above are true and accurate.
Signed:	[signature removed from digital version]
Date:	14/09/2018
Dr Biggs
As a supervisor for this postgraduate student I certify that the authorship attribution statements above are true and accurate.
Signed:	[signature removed from digital version]
Date:	14/09/2018
Dr Roberts
