# Introduction

## An expanding urban area

Urban areas only cover 0.5% of Earth’s terrestrial surface and yet are one of the fastest growing land use types on a per area basis (Gashu and Egziabher, 2018; Powell et al., 2007; Sexton et al., 2013). Population growth is fuelling urbanisation with 55% of the planet’s 7.6 billion people residing in urban areas in 2018, and which is expected to accommodate up to 68% of the global population by 2050 as a result of an estimated additional 2.5 billion people (Powell and Roberts, 2010; Sexton et al., 2013; Sharifi and Lehmann, 2014; United Nations, 2018). Land use and land cover change represent the main driving force in global environmental change, especially anthropogenic modifications from vegetated to impervious surface material, through which water does not infiltrate (Sundarakumar et al., 2012; Tan et al., 2009; Verburg et al., 2015). In order to accommodate the expected increase in population, urban area is predicted to triple by 2030 based on current trends, increasing total global coverage to 0.9% of Earth’s terrestrial surface (2000 baseline of 652,825 km2) (Seto et al., 2012). 

Urban growth, defined as the sum of the increase in developed land between two or more time periods, was traditionally thought of as an intrinsic process and metric of economic success (Sundarakumar et al., 2012). However, the benefits have now been carefully evaluated in conjunction with any adverse social, economic and environmental impacts. For example, continued outward expansion exponentially decreases resource efficiency due to vast infrastructural requirements, additional commuting time and household transportation expenditure (Batty et al., 2003; Downs, 2005). The alteration of natural land to impervious surfaces frequently induces the Urban Heat Island (UHI) effect whereby man-made urban areas obtain comparatively higher atmospheric and surface temperature than rural areas; the UHI effect is considered one of the major environmental problems posed to humans in the 21st century (Rizwan et al., 2008). In conjunction with expanding global urban areas and population growth the extent and magnitude of the UHI will continue to grow (Zhang et al., 2013). Furthermore, urbanisation can lead to income-based neighbourhood segregation which exacerbates social and ethnic divisions (Batty et al., 2003), and coupled with the UHI effect can result in sociodemographic-driven healthcare implications during heatwaves (Gronlund et al., 2015; Yu et al., 2010). Whilst urban expansion can generate benefits, accurate and timely information on the characteristics and associated impacts of urban expansion are critical for assessing current and future needs regarding urban growth and developing policy priorities for inclusive and sustainable [socioeconomic and environmental] development, as reflected in recent global initiatives e.g. the United Nations (UN) New Urban Agenda (UN-Habitat III, 2017), City Resilience Framework (CRF) (ARUP and The Rockefeller Foundation, 2015) and 2030 Sustainable Development Goals (SDGs) (Osborn et al., 2015). **The overall aim of this research is to demonstrate the application of EO data in quantifying urban growth and its impact on the UHI in order to illustrate its potential for informing both global and metropolitan sustainable city development goals.**

## Defining urban area

The term ‘urban area’ is surrounded by conceptual vagueness, with definitions varying based on discipline origin e.g. academia, census bureaus and metropolitan development agencies (Bennett, 2001). Weeks (2010) defined ‘urban’ as a characteristic of place whereby a spatially concentrated population are organised around non-agricultural activities. This definition is composed of (i) population size, (ii) land area, (iii) population density, and (iv) economic and social organisation. However, due to increased population movement towards traditional urban centres and subsequent outward expansion, the urban-rural divide is becoming difficult to differentiate (United Nations, Department of Economic and Social Affairs, 2014; United Nations, 2016; Weeks, 2010). In an effort to mitigate the increasing pressure from rural-urban migration on city expansion and metropolitan services developing countries have initiated schemes to attract urban infrastructure to previously considered rural areas (Weeks, 2010). For example, the Vietnamese government initiated side-line productions with the slogan “leaving the land without leaving the village” (Rigg, 1998; Weeks, 2010). Similarly, China’s Special Economic Zones (SEZs), offering corporations economic incentives, attempted to resolve socio-economic problems associated with the centrally administrated system whilst also importing a foreign knowledge base (Kam Ng and Tang, 2004). In 1980 the city of Shenzhen was designated as China’s first SEZ, originally considered a tiny rural town located at the northern edge of Hong Kong with a population of only 0.3 million. By 2000 SEZ status resulted in a 23 fold population increase to an estimated 7 million (Kam Ng and Tang, 2004; Zhou et al., 2016). Nevertheless it is difficult to exactly determine at what point in time Schenzen’s status changed from rural to urban due to the multitude of possible factors that could be considered (e.g. population, land area or economic organisation). 
Statistical bureaus define urban in various ways to ensure data availability for specific applications. For example, the Australian Bureau of Statistics (ABS) currently provide five definitions of urban area based upon differing Statistical Areas (SA) levels of collection. Due to the complexity of the ABS urban definitions they are summarised in Figure 1 1 (ABS, 2017). One important consideration within this framework is that the Greater Capital City Statistical Areas (GCCSAs) have only been in force since the 2011 census, replacing the statistical divisions that previously covered the greater metropolitan area, often referred to as the metropolitan region of each capital city constrained by Local Government Areas (LGA); consequently no previous census data is available for the complete GCCSAs (ABS, 2017).  

 
Figure 1 1. Varying urban definitions associated with different datasets produced by the Australian Bureau of Statistics (ABS). Adapted from ABS (2017).

Similarly the United States of America (USA) Census Bureau provides further urban definition variation (Figure 1 2). The USA Census Bureau base urban categorisation on census blocks, tracts, cities and counties. Census blocks are the smallest geographic census area, established from visible features such as roads, property boundaries and rivers. Census tracts are representative of neighbourhoods as defined by the Census Bureau, generally obtaining between 2,500 and 8,000 people, with boundaries also defined on visible features. Cities and associated spatial boundaries are defined in legislation by the city government whilst Counties are based upon geographic, political and administrative subdivision of a State (U.S. Census Bureau, 2018). 

 
Figure 1 2. Varying urban definitions associated with different datasets produced by the United States of America (USA) Census Bureau. Adapted from U.S. Census Bureau (2018).

In contrast the United Kingdom (UK) Office for National Statistics (ONS) rather more simplistically define urban as settlements with a population of 10,000 or more residents. Settlements are established from a grid of hectare cells (100m x 100m) over England and Wales, with residential properties inferred from Royal Mail’s (UK’s postal service) postcode address file assigned to cells. Residential density for a set of increasing radii surrounding each cell is calculated and compared to defined standards assigning each cell to a settlement type (e.g. village, town, urban fringe). Census Output Areas (OA), the smallest level of census data are combined with the classified cell output and defined urban if both classed as a settlement and obtaining a population of 10,000 or more (Bibby and Brindley, 2013).  


These contrasting urban definitions and associated data are based upon local governments and organisations being able to best identify features that differentiate urban and rural (Brockerhoff, 2000). Nevertheless individual country specific approaches hinder cross country comparison and accurate global estimates due to the multitude of differing factors that are considered in determining urban extent.   

Urban development strategies that outline future development and sustainability targets are frequently provided by metropolitan development agencies such as the Spatial Development Strategy For London (Mayor of London, 2016a), Perth’s Directions 2031 (Western Australian Planning Commission, 2010a) and Johannesburg’s Spatial Development Framework 2040 (City of Johannesburg Metropolitan Municipality, 2016). These documents often fail to definitively define the term urban, generating inconsistencies throughout national agencies. In the case of Perth, Western Australia (WA), initial urban estimates only covered the Perth Metropolitan Region (PMR) based upon cadastral land parcel valuations, with later estimates considering spatial modelling, multiple urban categories and the larger spatial extent of the Perth GCSSA (Western Australian Planning Commission, 2010a). Consequently, whilst the spatial extent of the defined metropolitan region or GCCSA will align with the ABS extents, urban estimations are derived from differing metrics.  
The main overall limitation of the aforementioned classifications pertains to the assumption of a dichotomous urban and rural divide. However, due to the wide variations in urban designation, the UN Population Division (1950) originally proposed an urban-rural continuum (Weeks, 2010). Nevertheless, of the 228 countries for which the UN compiles data, around half define urban extent based on administrative boundaries, 51 use population size or density, 39 implement financial metrics, 22 have no definition and 8 define all (e.g. Singapore) or none (e.g. Polynesian countries) as urban (Brockerhoff, 2000). A lack of consistent national and international urban definitions precludes scientifically valid comparisons (Brockerhoff, 2000). 

The advent of remote sensing provides an alternative approach for mapping urban areas. Sensors on board satellites provide consistent and reliable collection of data that when combined with approaches for classification can determine urban extent over time based upon unique and specific land cover characteristics. For this research urban is defined as a determinant of urban land cover as calculated from the spectral reflectance properties of temporally consistent user defined areas (termed Regions Of Interest (ROIs)) from satellite Earth Observation (EO) sensors: Landsat 5 Thematic Mapper (TM), and Landsat 8 Operational Land Imager (OLI). The reflected radiation monitored in each spectral band was combined in producing unique surface reflectance spectral signature for the ROIs subsequently matched to other similar pixels through classification methodologies. Due to the heterogeneity of urban areas and spectral confusion of classification methodologies associated with spectrally similar land cover classes (e.g. bare earth and urban) urban land cover was classified as either high or low urban albedo (Chen et al., 2014). The former represents surfaces with higher solar reflectivity (e.g. concrete) usually found in city centres whilst the latter denotes lower solar reflectivity (e.g. asphalt) commonly used in residential developments (Yang et al., 2015). 

In this sense urban area depicts land cover representing the biophysical attributes of Earth’s surface as opposed to land use that defines the human purpose or intent applied to the biophysical attributes (Lambin et al., 2001). Whilst this definition excludes population, economic and social organisation factors, it provides the longest temporal record of land cover derived from a replicable and temporally consistent methodology appropriate in determining further environmental relationships such as the association with temperature; important for planning (sustainable) development. Within this research development refers to an expansion of urban area based upon a change in land cover whilst sustainable is defined as actions causing minimal (or no) damage to the environment and humans enabling long-term continuation aligning with the UN’s combined sustainable development definition of development “that meets the needs of the present without compromising the ability of future generations to meet their own needs” (Brundtland, 1987, p.41).

## Types of urban expansion

### Urban growth

Within scientific literature urban growth is often conceptualised using a form of geographic data resulting in three main categories considering the relationship to existing urban areas, namely infill, expansion and outlying, with outlying obtaining three further sub categories of isolated, linear branch and clustered branch (Wilson et al., 2003; Yuan et al., 2005) (Figure 1 3). Infill growth is defined by the (re)development of a small land tract surrounded by urban land cover. Often characterised by the conversion of a non-developed area (e.g. 30 m2) to an urban surface with at least 40% of the surrounding area that is also defined as developed, usually occurring in areas of existing infrastructure (Bhatta, 2010; Wilson et al., 2003). Expansion growth constitutes conversion of non-developed area to developed, whilst being surrounded by no more than 40% existing developed area (Bhatta, 2010; Wilson et al., 2003). The overall limiting factor of these characterisations pertains to the assumption of conversion from non-developed land (known as a greenfield site), when other urban land cover could be converted from dormant use (e.g. wasteland or abandoned facilities, known as a brownfield site) to a form infill development. However, this type of conversion is difficult to determine without land use information accompanying geographic data. Outlying growth occurs beyond the existing developed area, in the isolated form it is characterised by one or several developed areas surrounded by minimal developed land. The linear branch form refers to a new linear development (e.g. roads) that are surrounded by non-developed areas. Finally the clustered branch form identifies large compact developments that are neither isolated nor linear in nature (Wilson et al., 2003).
 
Figure 1 3. Forms of urban growth as defined by scientific literature. Adapted from Bhatta (2010).

In contrast to academic literature, previously presented metropolitan level policy documents in section 1.2 stipulate infill targets and aspirations but often omit urban growth definitions providing no further subcategories (e.g. Perth and London) or vague definitions (e.g. Johannesburg) that are difficult to quantitatively assess. For example, the Johannesburg Metropolitan Municipality specified a linear future development scenario defined based on concentration of population and jobs along extensive transit corridors, but lack a measureable metric that would provide adequate monitoring. Whilst the Western Australian Planning Commission (WAPC) aim to achieve 47% of future development as infill by 2050, monitoring considered zoned and not necessarily developed industrial, commercial and residential land use defined as infill or greenfield based upon residential density above or below an unspecified threshold using census data (Western Australian Planning Commission, 2016a). In Australia, census data is collected every 5 years, restricting temporal monitoring of development and assuming that changes in density across a range of land use types that may not yet be developed is an accurate representation of infill development (Western Australian Planning Commission, 2016a). The vagueness associated with current policy definitions initiates difficulties for local governments in meeting specified targets and in the provision of policy-focused methodologies to accurately monitor urban development.  

###	Urban sprawl

The expansion of low density suburbs into previously rural areas creates exurbs, urban or suburban areas and raises the notion of urban sprawl (Sun et al., 2013; Yuan et al., 2005). Currently there is no universally accepted definition of urban sprawl, with multiple studies using urban growth, urban sprawl, peri-urbanisation and exurban development interchangeably without providing definitive definitions (Schneider, 2012; Schneider and Mertes, 2014; Suarez-Rubio et al., 2012; Xian et al., 2012). Whilst Yuan et al. (2005) highlighted the requirement of an undeveloped land buffer between established area and new development, Castrence et al. (2014) simply stated urbanisation is a loss of open space and agricultural land that leads to urban sprawl. In terms of previously considered metropolitan policy documentation only Johannesburg provided a definitive sprawl definition revolving around dispersed over focused developed forms, whereas Perth’s implied low density, greenfield detached housing dwellings located on the urban fringe and London’s suggested development beyond the greenbelt. Consequently in a similar theme to urban growth, policy orientated urban sprawl ambiguity produces difficulties for both local governments and researchers in monitoring and identifying solutions when the very concepts aren’t defined by metropolitan agencies.   
Defining urban sprawl as a concept has highlighted ambiguity and conceptual vagueness (Bennett, 2001; Bhatta, 2010; Bhatta et al., 2010). Galster et al. (2001) undertook an extensive evaluation of sprawl within the literature that revealed sprawl can be alternatively or simultaneously referred to as patterns of land use, processes of land development, causes of land use behaviours and consequences of land use behaviours (Bhatta, 2010; Bhatta et al., 2010; Galster et al., 2001). Furthermore, to add to the complexity, sprawl is also referred to as a noun and a verb. As a noun it signifies a condition representing an urban area at a particular time, whereas when used as a verb it defines a stage or process of development (Bhatta, 2010; Galster et al., 2001). Whilst a definitive definition of sprawl is contested, a general academic consensus exists that urban sprawl is characterised by unplanned and uneven pattern of growth resulting in inefficient resource utilisation (Bhatta, 2010; Bhatta et al., 2010; Sun et al., 2013), which is the definition followed in this research.
1.3.3	Urban growth and sprawl in Earth observation
It is important to establish that every type of urban growth should not be considered sprawl (Bhatta, 2010). Whilst the notion of sprawl attracts a negative connotation in terms of environmental and societal impacts, types of urban growth such as infill development are considered resolutions to urban sprawl. Consequently, sprawl should not be used interchangeably with urban growth and must be considered as its own separate entity. However, within EO studies this is often unfeasible due to similarities of materials and geometries that compose both urban sprawl and urban growth being indiscernible using medium resolution EO imagery. Therefore the majority of studies focus on monitoring urban growth as a holistic concept (which could encompass sprawl) as being the change in developed land between two or more time periods (e.g. Luo et al., 2014; Schneider and Mertes, 2014; Sexton et al., 2013; Song et al., 2016).
1.4	The urban heat island effect
1.4.1	Introduction
One of the main environmental impacts of urbanisation is the UHI effect, whereby urban areas obtain comparatively higher atmospheric and surface temperatures than surrounding rural areas (Cai et al., 2016; Howard, 1988; Hu and Brunsell, 2015; Voogt and Oke, 2003; Xie and Zhou, 2015). The modification of land cover properties as a result of urbanisation has been identified as the most extreme cumulative effect of land cover change, permanently influencing atmospheric energy exchange and altering local and regional climate change (Cai et al., 2016; Howard, 1988; Hu et al., 2015; Voogt and Oke, 2003; Xie and Zhou, 2015). Thus, UHIs are considered one of the major problems posed to humans in the 21st century, with the importance of understanding heat risk highlighted by extreme temperatures overtaking flooding and rising to the third highest cause of global disaster mortality (11.3%) between 2006 and 2015, behind only earthquakes (51.2%) and storms (24.9%) (Centre for Research on the Epidemiology of Disaster and the United Nations Office for Disaster Risk Reduction, 2016). 
1.4.2	Urban heat island theory
The UHI phenomena is created through a shift in energy balance toward sensible heat over latent heat. The former represents heat exchanged by a body that changes temperature (e.g. conduction, convection or advection) whilst the latter is defined as energy released or absorbed by a body (e.g. evapotranspiration) (Sexton et al., 2013; Wong et al., 2013). The creation of UHIs is the result of two major factors: an increased spatial coverage of dark surfaces and the absence or removal of vegetation (Frumkin, 2002; Voogt, 2004). Dark urban surfaces obtain a low albedo (albedo being the fraction of shortwave radiation reflected from an object, in comparison to natural surfaces). Consequently, impervious surfaces (such as asphalt and concrete) absorb and retain a large proportion of the shortwave radiation during the daytime, reemitting this energy as long wave energy (or sensible heat) during the day (based on surface properties) and particularly at night (Zhao et al., 2016). However, due to the three dimensional structural arrangement of modern cities, a low Sky View Factor (SVF), defined as the ratio of radiation received (or emitted) by a planar surface to the radiation emitted (or received) by the entire hemispheric environment, frequently precludes efficient heat dispersion (Abutaleb et al., 2015; Frumkin, 2002; Kalnay and Cai, 2003; Lindberg and Grimmond, 2010; Sharifi and Lehmann, 2014; Voogt, 2004; Watson and Johnson, 1987; Zhao et al., 2016). The absence or removal of vegetation reduces solar radiation blocking to urban surfaces which inhibits heat emittance, diminishing evapotranspiration that cools the atmosphere through ambient heat dissipation (Frumkin, 2002). Further factors including air speed, cloud cover, cyclic solar radiation, building material type and anthropogenic energy sources can exacerbate this phenomena in a temporary (e.g. weather patterns) or more permanent (e.g. built environment) manner (Rizwan et al., 2008; Sheng et al., 2015). 
Contributing UHI factors are commonly described through the energy balance equation whereby net radiation, defined as the balance between incoming and outgoing energy at the top of the atmosphere equates to the sum of sensible heat (energy heating the air), latent heat (energy used for evaporation) and surface conductive heat (energy heating the ground) fluxes. When applying the energy balance equation to UHI concepts sensible heat is representative of building thermal properties, latent heat is a function of vegetation coverage and surface conductive heat is dependent on surface albedo. Recent iterations have also included anthropogenic heat sources, representative of systems that emit heat such as air-conditioning and automobiles combined with net radiation equating to the sum of surface, latent and conductive heat fluxes (Arnfield, 2003). 
1.4.3	Urban heat island categories
This section describes UHI categories and temporal forms, enabling appropriate terminology inclusion when discussing monitoring approaches leading to identification of current research and policy issues in relation to global and metropolitan sustainable city development goals, the latter part of the overall thesis aim.
1.4.4	Heat island layers
The UHI concept can be decomposed into three subcategories: the Boundary Layer Heat Island (BLHI), the Canopy Layer Heat Island (CLHI) and the Surface Heat Island (SHI) (Figure 1 4). BLHI and CLHI refer to warming of the urban atmosphere, with SHI indicating urban surface heat (Fabrizi et al., 2010; Voogt, 2004). The UCL and SHI are both located within the Urban Boundary Layer (UCL), extending up to around 1 km or more above the surface during daytime and shrinking to around hundreds of meters or less at night. The UCL is the layer of air closet to city surfaces 
