# Research aim and objectives 

This short chapter outlines the overall research aim and objectives of this thesis. The aim of this research is to demonstrate the application of Earth Observation (EO) data in quantifying urban growth and its impact on the Urban Heat Island (UHI) in order to illustrate its potential for informing both global and metropolitan sustainable city development goals. In achieving this aim the research objectives are extracted from current themes and gaps, presented both in the main thesis introduction and in each paper style chapter. This is divided across the four paper style chapters each addressing their own objectives: 

1. Provide a remotely sensed spatio-temporal assessment (paper 1a, chapter 4) and associated methodology (paper 1b, chapter 4) of change in urban area across the Perth Metropolitan Region (PMR) using a consistent methodology. 

2. Develop an approach to remediate frequent over (or under) estimation of urban area classified from medium resolution satellite imagery through comparison to very high resolution aerial imagery — paper 2, chapter 5.

3. Investigate the spatio-temporal UHI characteristics at the sub-metropolitan level using a per pixel approach through (a) determining the complexities of the UHI effect and (b) deriving associations between land cover and temperature change at the intra-urban scale — paper 3, chapter 6.

4. Establish an operational methodology for evidence-based urban planning to optimise localised UHI mitigation through the use of EO data and open source spatial temperature models — paper 4, chapter 7. 

## Study site

This section provides an introduction and overview to the PMR in Western Australia (WA), the study site used throughout this thesis in achieving the objectives and overall aim. The City of Perth is the State Capital of WA and has undergone dramatic urban and population growth accredited to Australia’s natural resources boom commencing around the start of the 21st century. Mining and petroleum exports dominate WA’s export products attributing 95% of export earnings between 2010 and 2011, with sales rising from AUD 4.7 billion in 1996 to a peak of AUD 121.6 billion mid-2013 (Department of Mines and Petroleum, 2015). The majority of the urban growth has been identified as sprawling, outward and low-density by the Western Australian Planning Commission (WAPC) (Western Australian Planning Commission, 2015a). This is representative of the ‘Australian dream’ comprising of detached living within a green suburb on greenfield urban-fringe sites (Dhakal, 2014; Western Australian Planning Commission, 2015a). Consequently in comparison to other Australian state capitals Perth was Australia’s fastest growing city (in terms of population) between 2007 and 2014 whilst only obtaining a maximum population density of only 3,662 people per square kilometre (Melbourne 10,827; Sydney 14,747)  (ABS, 2015, 2011; Kennewell and Shaw, 2008). The pressures from this extensive low density and outward expansion has induced non-strategic and car centric development that has the potential to degrade social and environmental systems such as amenity servicing efficiency and habitat loss (Dhakal, 2014; Downs, 2005; Turner et al., 2010). The guide for the long term (2050) development of Perth specifies that future land rezoning must be the result of strategic urban planning as opposed to individual requests (Western Australian Planning Commission, 2015a). However, current urban monitoring within the PMR is based upon unrepresentative (e.g. land value information) and temporally varied data. Thus, owing to PMR’s vast and rapid expansion alongside a globally diverse range of urban characteristics (e.g. compact central business district, older residential areas and new suburban developments) it provides a timely and relevant example to develop innovative solutions in determining temporally consistent urban area models whilst remediating frequently reported over (or under) urban estimation from medium resolution imagery.

In a similar theme under the sustainability key strategy within the long term development guide, recently devised metropolitan and local temperature mitigation plans use limited and/or aggregated data which could misguide remedial actions (Western Australian Planning Commission, 2012). Based on the lack of global investigation into the causes and consequences of the metropolitan and local UHI effect alongside Perth’s large scale conversion of natural to impervious surfaces it provides a unique and globally important case study in resolving current limitations of expanding urban areas and their association to temperature. More specific information pertinent to each objective can be found within each paper style chapter, with further contextual study area information provided in chapter 4.

##	Thesis structure and methodological outline

This thesis is composed of nine chapters including two introduction chapters, this aim and objectives chapter, four chapters presented in the form of scientific journal articles aligning with the ‘three-paper’ format PhD submission, a discussion and final conclusion chapter. Each paper style chapter is taken from a published or submitted journal article, with minor editing to ensure consistency throughout the thesis. Whilst each paper explores unique research aims, Figure 3 1 outlines inter-linkages between the collective papers forming a coherent body of novel research contributions. Specifically temporal land cover data produced within the first paper is used within paper 2 and 3, with analysis from paper 3 informing paper 4 (Figure 3 2).

 
Figure 3 1. Outline of general thesis structure and paper linkages.
 
Figure 3 2. Data flow and linkage throughout papers presented in thesis.

Following this thesis introduction and literature review chapter 4 provides an applied example into using EO data for monitoring urban expansion in the city of Perth, WA. The implications of a rapidly expanding urban area are discussed and EO derived estimates are compared to those provided by the WAPC based upon temporally varied methodologies. This study provides the first EO temporal examination of land cover within Perth from normalised satellite imagery highlighting the applicability of EO data in accurate urban quantification for sustainable targeted planning practices and addressing the first thesis objective. 

Building on the work in chapter 4, chapter 5 further analyses classified hard and sub-pixel 2007 land cover data in relation to classified high resolution (20 cm) aerial imagery. The hard classification refers to the dominant land cover within each Landsat pixel, whilst the sub-pixel classification represents the probability of a pixel containing a classification value. High resolution imagery was classified using Object Based Image Analysis (OBIA) and aggregated to Landsat pixels (30 m) producing the percentage of land cover and identification of the dominant land cover class per Landsat pixel area. Firstly, the two hard land cover datasets were compared, identifying overestimation from the Landsat classification. Addressing errors of this nature are essential owing to EO land cover data being used to influence policy decisions. Overestimation was remediated through the implementation of novel spatially explicit regression model approach between the high resolution percentage urban per Landsat pixel and the Landsat sub-pixel data that improved urban land cover estimations from medium resolution imagery, achieving the second thesis objective. 

Chapter 6 uses 2003 and 2013 classified land cover data produced in chapter 4 alongside temperature data from the MODIS Terra sensor. The methodology overcomes current limitations of UHI studies such as use of temporally static land cover, assumption of urban homogeneity and disregard of a spatial component through global indices, inappropriate for policy incorporation. Land cover estimates were aggregated to MODIS resolution (1 km) producing the percentage of land cover per MODIS pixel for both 2003 and 2013. The dominant land cover change per MODIS pixel was identified and associated with the difference in temperature between 2003 and 2013. Consequently the presented novel analysis established ideal future land rezoning in relation to temperature change, accomplishing the third thesis objective.

Chapter 7 draws upon chapter 6 analysis in demonstrating an improved localised UHI mitigation approach. Current global, metropolitan and localised mitigation policies and strategies often fail in planning practicality through a lack of specificities or inappropriate data use. Chapter 7 demonstrates the power of EO data and spatial modelling in reducing localised temperature for a proposed redevelopment in the City of Fremantle, WA through optimum vegetation placement using a scientifically valid and policy integratable approach, advancing current policy and academic mitigation attempts, aligning with the final objective of this thesis. 

Chapter 8 critically discusses the research significance, methodological transferability, global applicability, current critical challenges and future research potential.   
Chapter 9 provides a summary of the key findings of the thesis in relation to the overall thesis aim. 





