# Urban growth dynamics in Perth, Western Australia: using applied remote sensing for sustainable future planning

## Abstract

Earth observation data can provide valuable assessments for monitoring the spatial extent of (un)sustainable urban growth of the world’s cities to better inform planning policy in reducing associated economic, social and environmental costs. Western Australia has witnessed rapid economic expansion since the turn of the century founded upon extensive natural resource extraction. Thus, Perth, the state capital of Western Australia, has encountered significant population and urban growth in response to the booming state economy. However, the recent economic slowdown resulted in the largest decrease in natural resource values that Western Australia has ever experienced. Here, we present multi-temporal urban expansion statistics from 1990 to 2015 for Perth, derived from Landsat imagery. Current urban estimates used for future development plans and progress monitoring of infill and density targets are based upon aggregated census data and metrics unrepresentative of actual land cover change, underestimating overall urban area. Earth observation provides a temporally consistent methodology, identifying areal urban area at higher spatial and temporal resolution than current estimates. Our results indicate that the spatial extent of the Perth Metropolitan Region has increased 45% between 1990 and 2015, over 320 km2. We highlight the applicability of Earth observation data in accurately quantifying urban area for sustainable targeted planning practices. 

## Introduction

Over the last 15 years, Perth has experienced exponential economic growth with Gross State Product (GSP) increasing 218% (ABS, 2015). Originally labelled as the ‘Cinderella State’ due to its remote location and perceived neglect from the rest of Australia, Western Australia (WA) has experienced sustained discovery and extraction of natural resources since the beginning of the 21st century (Kennewell and Shaw, 2008). In response to a growing resource sector, the city of Perth has undergone extensive urban expansion at what Dhakal (2014) identified as an unsustainable rate. To this end, the Western Australian Planning Commission (WAPC) identified that Perth’s urban footprint has increased from 631 km2 to 870 km2 in the 10 years between 2002 and 2012 (Western Australian Planning Commission, 2010a, 2015a). However, these figures should be considered with caution as data used in early estimates represent land parcel (Cadastral) valuations only (provided by the Western Australian Value General’s Office), with later estimates (from 2009) based on multiple urban zoning classifications, and more recently (from 2010) spatial modelling taking into account land valuation and zoning (Western Australian Planning Commission, 2010b, 2009). The use of varied data and methods impacts confidence in the ability of the Commission’s estimates to represent actual change in urban extent, especially when urban zoning information includes land identified for growth but not necessarily developed. Such inconsistencies could have potential to misinform future development decisions. Consequently, here we present a spatiotemporal assessment of change in areal urban growth based upon medium resolution remote sensing through a single classification model. This provides the first accurate depiction of urban expansion for one of the world’s fastest growing cities—Perth, WA. We present our findings and discuss the implications of more accurately classified urban extents in facilitating scientifically evidence-based adaptive and targeted planning policies to help reduce environmental and socio-economic consequences of poorly planned development.

### Earth observation for monitoring urban change

Mapping the spatial extent and temporal profile of urban growth from medium resolution satellite imagery facilitates a consistent, detailed characterisation of the actual urban footprint of a city (Angiuli and Trianni, 2013; Bagan and Yamagata, 2012b). Other conventional spatial datasets such as Cadastral data provide information on freehold and Crown land parcel boundaries including attributes such as ownership and value for a singular temporal period (Thompson, 2015). However, attributed data for a singular year provides an ineffective portrayal of actual parcel land cover and temporal change. Thus, the methods and results presented in this study provide foundational information for the development of planning regulations that ensure sustainable growth of our cities, particularly in the reduction of environmental risks from ever-increasing expansion along the wildland–urban interface (Turner et al., 2010). Specifically, Earth Observation (EO) data allows spatially detailed identification of locations where (un)sustainable urban growth is occurring which enables expansion limits to be imposed through targeted policies (Bettencourt and West, 2010). In this theme, Schneider et al. (2005) determined the spatial distribution of development zones from 1978 to 2002 in Chengdu, Sichuan province, China in response to the Go West policy of the 1990s, aimed at economically boosting the West of the country. Whilst the policy was successful in raising Gross Domestic Product (GDP) levels, urbanisation concurrently increased, generating issues of urban management, including service, infrastructure and resource deficiency. Their results indicated spatial clustering, specialisation of land use and peri urban development (not considered by the original policy) which were subsequently used to tailor policy in remediating issues, facilitating sustainable future urban development (Patino and Duque, 2013; Schneider et al., 2005). Similarly, Hepinstall-Cymerman et al. (2013) used classified Landsat data to monitor urban growth in regards to imposed growth boundaries in the Central Puget Sound, Washington, United States of America. Surprisingly, more new development occurred outside the growth boundaries than inside within their last time period, illustrating the ineffectiveness of the imposed policy leading to economic and ecological consequences, including a loss of avian diversity in native forest species (Hepinstall-Cymerman et al., 2013; Hepinstall et al., 2008). These studies highlight the potential effectiveness of EO data in consistently monitoring the spatiotemporal dynamics of urban development for applied policy outcomes and ensuring sustainable future planning decisions, for which such outputs are unachievable from traditional datasets. 

### The case of Perth

Perth’s dramatic urban expansion can be attributed to Australia’s minerals and energy boom commencing at the turn of the century. Queensland (QLD) and WA were at the forefront of the boom contributing the largest proportion of the nation’s resources output, valued at 3.3% of GDP (ABS, 2015). In WA, mining and petroleum extraction dominate exports, peaking at 95% of the state’s export earnings between 2010 and 2011 (Department of Mines and Petroleum, 2015). The increase in extraction was predominantly attributable to greater demand for raw materials from China, resulting in steady growth of the WA mineral and petroleum industry from AUD 4.7 billion in 1996 to a peak of AUD 121.6 billion mid-2013. However, in 2009, a 10.3% reduction in the overall value of mineral and petroleum resources resulted from falling commodity prices and the 2007–2009 global financial crisis (Department of Mines and Petroleum, 2015). Again in 2012, a further 9% reduction in resource value was observed as uncertainty in global economic conditions increased (Department of Mines and Petroleum, 2015). The largest decline to date occurred between 2014 and 2015, with an additional 22% reduction in the value of mineral and petroleum resources as a result of surplus capacity, decreased demand, and decline in the value of the Australian dollar (Department of Mines and Petroleum, 2015). The temporal trend in resource value indicates a stagnation and decline since late 2013 (Figure 4 1). 



 
Figure 4 1. Timeline of natural resource value (based on Department of Mines and Petroleum annual reports) fitted with a fourth order polynomial trend line and population (based on Australian Bureau of Statistics data) also indicating key milestones.

Perth is described as one of the most isolated cities in the world (pop. > 1 million) and was Australia’s fastest growing metropolis between 2007 and 2014; however, subsequent to a decline in natural resource value, a slowdown in population expansion soon followed (Figure 4 1) (Kennewell and Shaw, 2008). As a result, 2015 population statistics highlight the lowest population increase since records began with a 0.5% increase from the previous year (ABS, 2015; Kennewell and Shaw, 2008). In comparison to other Australian state capitals, based on the Australian Bureau of Statistics (ABS) 2011 population grid, Perth exhibits a relatively sparse spatial distribution of population with a maximum population density of only 3662 people per square kilometre (Melbourne 10,827; Sydney 14,747). Such low density population has generated high demand for dispersed housing, amenities and services, and has influenced changes to Perth’s land use patterns in a non-strategic, “lot-by-lot fashion” based on a car-dependent lifestyle (Dhakal, 2014). Anthropogenic modifications of the landscape from vegetation cover to human-made impervious surfaces represent a critical driving force in both local and global environmental change (Kalnay and Cai, 2003; Vitousek et al., 1997). For example, abrupt, poorly planned and uncontrolled urban expansion can lead to environmental impacts which degrade ecological systems including habitat fragmentation and socio-economic issues that deteriorate efficiency of amenity provisioning, both of which can exacerbate localised climate change (Downs, 2005; Turner et al., 2010). Identifying impacts of Land Use and Land Cover (LULC) change on socio-ecological systems is vital for future sustainable urban development; as reflected in the “sustainable cities and communities” 2030 sustainable development goal and the effective land use planning criteria of the City Resilience Framework (CRF) (ARUP and The Rockefeller Foundation, 2015; Vitousek et al., 1997). It is essential for Perth to adapt current practices of outward suburban expansion to achieve more sustainable urban growth and become city-smart for accommodating the predicted additional half a million new residents by 2031, which will result in an overall population exceeding 2.2 million (Western Australian Planning Commission, 2010a). 

## Materials and methods

### Data preprocessing

EO data have been extensively used to monitor the sustainability of urban areas (Li et al., 2015; Song et al., 2016). However, accurate identification and temporal monitoring of urban land is frequently precluded due to the coarse resolution (300 m–1 km) of a number of commonly used remotely sensed datasets including nighttime lights (1 km) and the Moderate Resolution Imaging Spectroradiometer (MODIS) land cover product (0.083°) (Potere et al., 2009; Song et al., 2016). Whilst 30 m resolution data (e.g. Landsat) are more suitable to detect nuances of urban development the majority of studies and classified products which have used these finer resolution products implement large temporal windows, negating the possibility of detailed temporal urban characterisation (e.g. GlobeLand30, Hu et al., 2015; Masek et al., 2000; Suarez-Rubio et al., 2012; Van de Voorde et al., 2011; Xian et al., 2012). This research provides the first comprehensive temporal evolution analysis quantifying land cover change and associated urban expansion for the Perth Metropolitan Region (PMR) using 30 m Landsat imagery, the longest temporal record of medium spatial resolution imagery, for seven sequential time snapshots between 1990 and 2015. 

Cloud free imagery was acquired in or close to the month of July for 1990, 2000, 2003, 2005, 2007, 2013 and 2015. Analysis of imagery acquired from WA winter season coincided with peak green-up which provided the greatest contrast between spectrally similar surfaces (e.g. bare earth and urban) (Herold et al., 2002; Lu et al., 2011; Varshney and Rajesh, 2014). Imagery date selection was founded upon the strong positive relationship between Australian soil moisture (related to rainfall) and the Normalised Difference Vegetation Index (NDVI) (Chen et al., 2014), which exhibits an approximate one month lag between peak soil moisture and peak NDVI (Chen et al., 2014). 

Productive photosynthesising plants use energy in the visible red (VIS) portion of the electromagnetic spectrum whilst reflecting in the near-infrared (NIR) region. NDVI ((NIR -VIS)/(NIR + VIS)) is a representative measure of growth allowing for the identification of green, healthy vegetation (Chen et al., 2014; Myneni et al., 1997; Piao et al., 2011), as illustrative of Southwest WA’s winter months. A total of 14 images from Landsat 5 Thematic Mapper (TM) (eight images), Landsat 7 Enhanced Thematic Mapper Plus (ETM+) (two images) and Landsat 8 Operational Land Imager (OLI) (four images) were acquired for the specified years. Seamless images were produced based on Voroni diagrams that locate the bisector between images; adjacent edges were identified as seamlines constraining effective mosaic polygons that specify inclusion pixels for the final mosaicked product, permitting less visible boundaries through blending overlapping pixels (Pan et al., 2009). Mosaicked images were subsequently clipped to the original PMR study area boundary. 

The atmospherically corrected Landsat data used in this study were obtained from the Landsat Ecosystem Disturbance Adaptive Processing System (LEDAPS) and the Landsat 8 Surface Reflectance (L8SR) algorithm (Hansen and Loveland, 2012; USGS, 2015). Some inherent residual noise remained, for example, due to the differences in modelled atmospheric correction parameters (Ju et al., 2012). To correct for this, surface reflectance values were standardised as:

p_(i,b)=p_(x,b)/〖max〗_b 	(4.1)

where p_(i,b) is the standardised pixel value i, from band b based on the original surface reflectance x, standardised through division of a priori specific upper reflectance limit for each band (maxab): 0.1 (blue; 0.48 µm), 0.11 (green; 0.56 µm), 0.12 (red; 0.66 µm), 0.225 (near-infrared; 0.84 µm), 0.205 (shortwave-infrared; 1.65 µm), 0.150 (shortwave-infrared 2; 2.22 µm) (Sexton et al., 2013). Standardised values were then normalised per pixel j through cross band sum division:

p_(j,b)=p_(i,b)/(∑_i▒p_(i,b) )	(4.2)

where ∑_i▒p_(i,b)  is the sum of each standardised pixel across all bands (Sexton et al., 2013). Normalised Landsat data obtained a statistically significant reduction of spectral variation per land cover class within (inter) and between (intra) each image (see Supplementary Figure 4 5).

### Data classification

The normalised Landsat imagery was classified using the Import Vector Machine (IVM) which builds upon the popular Support Vector Machine (SVM) methodology (Roscher et al., 2012). In order to obtain the optimum classification, the IVM algorithm explores all possible subsets of training data for optimal selection (termed import vectors) which are derived through successively adding training data samples until a given convergence criterion is met (Roscher et al., 2012). Data samples are selected according to their contribution to the classification solution. However, a pure forward system is unable to remove import vectors that become obsolete after addition of other vectors. Therefore the implemented version of IVM utilised here is a hybrid forward/backward strategy that adds import vectors whilst concurrently testing if they can be removed in each step, thus leading to a sparse and more accurate solution (Roscher et al., 2012). Furthermore, the IVM selects data points from the entire distribution resulting in a smoother decision boundary which is based on the optimal separating hyperplane in multidimensional space compared to that of SVM algorithms (Braun et al., 2012). The benefits of the IVM algorithm have resulted in this approach being successfully applied in a number of studies (e.g. Braun et al., 2012, 2011; Roscher et al., 2010; Suess et al., 2014) due to its accuracy and performance advantages over alternative methodologies including SVM and the traditional Maximum Likelihood (ML) classifier (Braun et al., 2011; Roscher et al., 2010).

Model training samples were selected using the July 2005 Landsat 5 TM image coinciding with the month post maximum rainfall of all considered Landsat 5 TM and 7 ETM+ to facilitate optimum spectral seperability (Chen et al., 2014). Land cover was defined as high albedo urban (e.g. concrete), low albedo urban (e.g. asphalt) or other. Two urban classes were initially identified in order to reduce confusion between spectrally similarly classes (e.g. urban and bare earth) being merged post-classification to represent complete urban coverage (Hu and Weng, 2009). For each class, 250 pixels were randomly selected as training data, which is consistent with Foody and Mathur (2006) and Pal and Mather (2003) (see supplementary section 4.7.2). Training data parametrised the IVM algorithm, creating a classification model of spectral profiles that are compared to Landsat spectral profiles for classification. The classification model was then applied to all Landsat 5 TM and Landsat 7 ETM+ images obtaining similar spectral wavebands, considered to be equivalent (Flood, 2014). However, due to Landsat 8 OLI sampling different spectral regions, a new classification model was developed using the same training areas, as these were deemed to remain representative of the land cover, but with Landsat 8 OLI spectral wavebands (Flood, 2014; Roy et al., 2016). Validation was performed through an accuracy assessment based on an independent dataset (Google Earth high resolution imagery) consistent with Landsat acquisition months following previously published methods (e.g. Bagan and Yamagata, 2014; Cunningham et al., 2015; Dorais and Cardille, 2011; Song et al., 2016; Sun et al., 2015; Zhu and Woodcock, 2014). For each land use category, 50 pixels per class per year were visually identified and classified based on the majority land cover within the coincident Landsat pixel from Google Earth imagery for the available years 2000, 2003, 2005, 2007, 2013 and 2015 consistent with recommended land cover accuracy sample size of Congalton (2001). 

## Results
The spatial footprint of PMR development has increased 48.61% between 1990 and 2015, over 320 km2 (Figure 4 2 and Figure 4 3), with a 40.56% increase occurring since 2000. The classification accuracy assessment indicates an average overall accuracy of 81.06% and Kappa Coefficient of 0.73 being comparable to other studies (e.g. Bagan and Yamagata, 2014; Gislason et al., 2006; Luo et al., 2014; Sundarakumar et al., 2012) (see Supplementary Table 4 1 and Supplementary Table 4 2). Urban expansion mirrors population increase and as population growth has slowed, urban development has concurrently exhibited a levelling trend compared to expansion previously observed (Figure 4 3). 

 
Figure 4 2. Urban expansion within the Perth Metropolitan Region (PMR) between 1990 and 2015. Vast urban growth has been observed in PMR with graduating colours exhibiting outward expansion (a); (b) and (c) exhibit static snapshots of urban extent from 2000 (b) and 2015 (c); whilst (d) depicts percentage of urban change per subnational administrative boundary (Local Government Area (LGA)).


 
Figure 4 3. Time line of urban expansion in kilometers squared derived from Earth observation data with associated classification error derived from validation data (points indicating classified image years). Alongside population data in millions per year since 1988 (based on Australian Bureau of Statistics data, 2015 data is projected) with key natural resource milestones indicated, and average annual urban and average annual population growth rate indicated between classified image years.

WAPC’s urban estimates of the PMR from Directions 2031 (the strategic plan for the Perth and Peel region) were provided for comparison to those produced within this study (Western Australian Planning Commission, 2010a). WAPC’s estimates note an expansion from 637 km2 to 813 km2 between 2001 and 2012. Our results indicate an expansion of 747.41 km2 to 1050.57 km2 from 2000 to 2013 illustrating an overall underestimation by WAPC figures (Figure 4 4). Within suburban areas surrounding the two major cities in the metropolitan region, Perth and Fremantle, WAPC’s estimates underrepresent the amount of urban area derived from EO, being more pronounced in 2013 than 2000. The Local Government Area (LGA) of Stirling South Eastern (LGA outlines displayed in Supplementary Figure 4 6) represented the maximum overestimation in 2013 urban area with 34.47% (2000: 9.95%) additional urban area per km2 of LGA established on a difference of 2.89 km2, 41.91% (2000: 0.83 km2, 14.99%) between EO data and WAPC’s estimates. Outer Northern and Southern LGA WAPC urban values were consistently underestimated, with the LGA of Belmont representing the maximum underestimation of percent per km2 of LGA in 2013 with 23.62% (2000: 12.60%) due to a difference of 9.37 km2, 40.39% (2000: 5.00 km2, 26.46%). Prior to 2009, WAPC’s estimates were solely based upon land parcel valuations from the Western Australian Value General’s Office, consequently valuation thresholds designating land to urban may have been inappropriately applied to outer suburban LGAs, where land might be developed but less valuable than central LGAs. 

For urban estimates post 2005, two urban land zones, urban and urban deferred, are used within the Perth Metropolitan Region Scheme (MRS), the division of the State Planning Policy Framework applicable to the PMR, pursuant to the Planning and Development Act (2005) that inform recent WAPC land parcel based estimates (Western Australian Planning Commission, 2016b, 2010c). Urban land refers to locations where activities in line with urban development are permitted, but not necessarily constructed (e.g. housing and commercial use) whilst urban deferred represents land suitable for future development with remaining planning, servicing or environmental issues (Western Australian Planning Commission, 2016a, 2010c). For land to be assigned urban deferred, it must obtain characteristics of the urban zone including being able to provide essential services, a logical progression of development, and able to satisfy regional requirements (e.g. roads and open spaces). The 2012 WAPC estimates were derived from stock of land zoned urban or urban deferred, cadastral land plot and value information, conditional subdivision approvals, and ongoing regional rezoning and subdivisions (Western Australian Planning Commission, 2012). Similarly to 2000, valuation data may misrepresent suburban urban land cover resulting in overestimation. Inclusion of additional variables that are unrepresentative of actual land cover change (e.g. rezoning and conditional approvals) could exacerbate differences between WAPC and EO derived urban estimates (Figure 4 4 (b)), leading to the potential confounding of errors in WAPC estimates.


 
Figure 4 4. Percentage differences relative to local government area size, permitting a change metric standardised by Local Government Area (LGA) area between Earth Observation (EO) and the Western Australian Planning Commission’s (WAPC) urban estimates for (a) 2000 (EO) and 2001 (WAPC) and (b) 2012 (WAPC) and 2013 (EO), whilst (c) depicts the percentage difference in the relative urban rate of change (km2 per LGA area) between 2000 and 2013 (EO) and 2001 and 2012 (WAPC). Positive values indicate underestimation by WAPC whilst negative values represent overestimation by WAPC.

## Discussion
WA state government planning documentation states that the majority of new development within the PMR has occurred as low-density suburban growth, responding to consumer preferences and market forces (Western Australian Planning Commission, 2015a). Additionally, sustainable policy objectives suggest that new development should be managed and focused on current communities, making the most efficient use of existing urban areas (Western Australian Planning Commission, 2010a, 2015a). Planning policy research has highlighted issues of outward urban expansion as being costly in economic, environmental and social terms based on dispersed service requirements, habitat fragmentation and neighbourhood segregation (Downs, 2005). Thus, urban expansion in the PMR may result in further economic, social and environmental costs associated with servicing and maintaining low-density lifestyles, owing to the rapid outward urban growth estimates between 2000 and 2007 (Downs, 2005; Turner et al., 2010). 

In contrast, the witnessed slowdown of urban growth, population and natural resource value since 2013 indicates the possibility that the ‘boom’ of previous years has reached a turning point. Stagnation of urban growth implies that issues associated with spatially distributed urban areas might be contained to the current urban extent. Nevertheless, it is conceivable that prosperous future economic circumstances could initiate growth at a rate previously observed, and that the economic slowdown might be a temporary hiatus responding to current economic conditions (Perry and Rowe, 2014). For example, in 2014–2015, WA continued to attract the largest proportion of state mineral exploration expenditure at 58%, with QLD (the second ranked stated) obtaining only 20% (Department of Mines and Petroleum, 2015). Furthermore, as of September 2015, WA had an estimated AUD 171 billion in mineral and petroleum projects under construction, with a further AUD 110 billion allocated for future expansion (Department of Mines and Petroleum, 2015). Comparatively, during the peak (mid-2013) in terms of total sales, WA only had an estimated AUD 160 billion worth of projects under construction and a further AUD 108 billion for future development (Department of Mines and Petroleum, 2015). Whilst 2014–2015 observed the greatest decline in total sales of resources, sustained investment and improved global economics could reinvigorate the industry and reinitiate urban expansion within the PMR.

Future development (urban and urban deferred) is guided by Directions 2031 amending the MRS and local planning schemes (Western Australian Planning Commission, 2015b, 2015c, 2015d, 2015e, 2010a). WAPC aims to achieve 47% of future development as infill and a 50% increase in average residential density by 2050 of 10 dwellings per urban zoned hectare and 15 per new urban zoned hectare (Western Australian Planning Commission, 2010a). In monitoring progress towards the infill target, zoned development land within the PMR is considered, including residential, industrial and commercial land uses (Western Australian Planning Commission, 2015a). Densities are defined as infill or greenfield if above or below an undocumented residential threshold from census data (Western Australian Planning Commission, 2016a). Initial results from Delivering Directions 2031, 2014 report indicate the requirement of a significant increase in infill development if the above targets are to be met (Western Australian Planning Commission, 2014). Similarly, average residential density monitoring has been achieved with land valuation data (from the Valuer General’s Office) for major activity centres, being unrepresentative of actual density change and providing an incomplete metropolitan comparison (Western Australian Planning Commission, 2014). Inclusion of EO data would permit quantitative evidence of urban expansion, infill and density at a higher spatial and temporal frequency than current census based estimates. This would facilitate credible, evidence-based efficient targeted action founded upon improved representative urban area, insuring infill and density attainment. In this theme, Schneider et al. (2005) and Hepinstall-Cymerman et al. (2013) used spatial metrics (e.g. urban area mean patch size) based on classified Landsat data in either pre-defined census units (Hepinstall-Cymerman et al., 2013) or development corridors (Schneider et al., 2005) to monitor development type (infill or expansion) over time for adapting inappropriate static urban development policy. Using EO derived land cover data in this manner aids in understanding dynamics of the urban environment through monitoring, planning and mitigating land use changes that impact natural assets and increase vulnerability of city systems (Hepinstall-Cymerman et al., 2013; Miller and Small, 2003; Patino and Duque, 2013). Information of this sort aligns with criteria of the CRF in improving city resilience from effective land use planning, possible at lower expense and higher temporal frequencies than in situ measurements (ARUP and The Rockefeller Foundation, 2015). 

The universal methodology implemented within this research lends itself to credibly inform policy in a similar manner in other global cities through monitoring urban expansion in order to identify rapid, unsustainable development. For example, Jakarta, obtaining the world’s second largest urban area with a population of 28 million, has yet to have any quantitative urban area delineation (Pravitasari et al., 2015; Seto et al., 2011). Identification of actual urban growth in developing cities is vital to city planners, environment managers and policy makers due to the difference between planned growth and actual growth (Patino and Duque, 2013). Such information could be of critical importance for regulating urban expansion due to extreme poverty and high level of risk to environmental hazards, such as that posed from flooding (Marfai et al., 2014; Suryahadi and Sumarto, 2003). EO data presents many opportunities for added value within urban planning policy, and additional analyses could be pursued into specific human-induced environmental issues, such as detecting thermal changes in the urban environment for planning issues associated with urban heat islands (e.g. cooling provisions) and their impact on human health (e.g. air quality).

## Recommendations 

Consistent and accurate LULC estimates are a vital aspect of sustainable urban development throughout the world, especially considering the predicted additional 2.5 billion city dwellers by 2050. LULC models that require agents that are representative of land use decisions can often fail in practicality due to the difficulty in quantifying driving forces of change and multi-level relationships. Models of this nature are also temporally independent, with each annual iteration implementing new data or data not representative of actual LULC change. EO data provides a replicable detailed representation of the complete urban extent requiring no additional data. The use and application of EO data reported within this paper highlights several improvements to WAPC policy for consistent urban area estimations with associated accuracy measures. Therefore it is recommended that planning authorities, such as WAPC, integrate EO data to achieve the following: (1) provide scientific urban estimates based on a temporally consistent model within future regional structure plans, metropolitan region and local planning schemes; (2) monitor infill development at a higher temporal frequency than census years for policy targeting to meet key goals; (3) monitor urban density through areal urban expansion compared to current metrics using land valuations; and (4) restrict development based on temporal urban analysis that degrades amenity efficiency and ecological systems whilst promoting development in locations to maximise efficiency and long-term sustainability. Additional EO datasets (e.g. finer resolution Sentinel 2 satellite imagery or aerial imagery) could be used to refine planning decisions based on areas of concern identified from Landsat. For example, finer spatial resolution datasets could facilitate enhanced feature extraction, optimising sustainable planning decisions through the identification of candidate infill sites. EO data of this nature provides an essential tool for timely planning policy that is adaptive to changes in urban landscape to mitigate socio-environmental issues associated with poorly planned urban areas for the future sustainability of our cities.

## Supplementary material 

This supplementary material section supports the main chapter and thesis through providing further detail into the summarised methods and results, pertaining to three concepts, namely the: standardisation and normalisation methodology, accuracy assessment and locations of Local Government Areas (LGAs). In the first instance a statistical comparison between the original un-corrected and corrected imagery is provided to highlight the reduction in inter and intra-year variance for land cover types demonstrating the validity of a single classification model for multiple years of imagery. Whilst key overall accuracy metrics are provided within the main chapter this supplement provides additional measures for each classified image for appropriate contextualisation if used by other researchers (accessible online). Similarly, Supplementary Figure 4 6 supports Figure 4 4 and text comparing estimates produced within the main chapter to that of the Western Australian Planning Commission (WAPC) through visually identifying the LGAs. A short discussion surrounding other considered approaches and a list of data used within the chapter are also provided to demonstrate the entirety of analytical process. 

### Standardisation and normalisation

The non-urban land cover class was composed of four classes defined based on existing literature (e.g. Feyisa et al., 2016; Hu and Weng, 2009; Schneider, 2012) and study area characteristics. These classes were forest, water, grassland and bare earth. Grassland and forest were also merged to create a single vegetation class. A complete set of land cover classes enabled examination of statistical differences generated from normalisation (Supplementary Figure 4 5). The Coefficient of Variation (CV) statistic was calculated to describe the amount of variability relative to the mean spectral reflectance of the post classification datasets (Brown, 1998). The CV was calculated for pre- and post-normalisation datasets for both intra-year class reflectance, which describes the variability within each class per year, and the inter-year reflectance, which describes the variability of each class across all imagery dates. Post-normalised Landsat data exhibited statistically significant lower inter- and intra-CV with T = 0, Z = −2.154, p = 0.016, r = −0.359 and T = 0, Z = −2.418, p = 0.008 r = −0.373, respectively. The test statistic (T) was obtained from dataset differencing (pre- minus post-processed images), representing the lowest value of the sum of positive ranks (values increased) or negative ranks (values decreased). Hence, T = 0 dictates that post-processed data consistently obtained a lower value than pre-processed imagery, statistically significant at p < 0.05 (Field, 2009). Therefore, reduced intra and inter year variance facilitates more appropriate one model classification for Landsat 5 TM and Landsat 7 ETM+ and another for Landsat 8 OLI.

 
Supplementary Figure 4 5. Inter year classification reflectance variation categorised by classified output for each spectral band for: pre (a) and post (b) normalisation correction.

### Accuracy assessment

For each land use category, 50 random pixels per class per year were visually identified and classified based on the majority land cover within the coincident Landsat pixel from Google Earth imagery for the available years: 2000, 2003, 2005, 2007, 2013 and 2015 (Congalton, 2001). Both user’s accuracy (fraction of correctly classified pixels relative to all others classified as a particular land cover), producer’s accuracy (fraction of correctly classified pixels compared to ground truth data) and associated Kappa coefficients were consistently high except for the producer accuracy of bare earth which has an average accuracy of 53.33% (Supplementary Table 4 1 and Supplementary Table 4 2). This is due to the known spectral similarities between bare earth and impervious surfaces, and water and shadow which resulted in spectral confusion during classification (Feyisa et al., 2016; Herold et al., 2002; Lu et al., 2011; Sawaya et al., 2003; Varshney and Rajesh, 2014).

Supplementary Table 4 1. Classification accuracy and associated Kappa Coefficient per year of classified Landsat.
Year	Accuracy (%)	Kappa Coefficient
2000	82.33	0.75
2003	80.33	0.72
2005	82.00	0.74
2007	84.00	0.78
2013	79.00	0.70
2015	78.67	0.70
Average	81.06	0.73

Supplementary Table 4 2. Producer’s and User’s accuracy per year of classified Landsat imagery.
Producer Accuracy	Bare Earth	Vegetation	Urban	Water
2000	56.00	96.00	90.00	66.00
2003	50.00	97.00	85.00	68.00
2005	52.00	98.00	86.00	72.00
2007	48.00	98.00	83.00	94.00
2013	52.00	99.00	81.00	62.00
2015	62.00	99.00	80.00	52.00
Average	53.33	97.83	84.17	69.00
User Accuracy	Bare Earth	Vegetation	Urban	Water
2000	84.85	76.80	84.11	94.29
2003	69.44	76.98	83.33	94.44
2005	81.25	78.40	81.13	97.30
2007	68.57	80.33	87.37	97.92
2013	68.42	73.88	83.51	100.00
2015	75.61	73.88	83.33	89.66
Average	74.69	76.71	83.80	95.60
Local government areas
 
Supplementary Figure 4 6. Local Government Areas (LGAs) located in Perth Metropolitan Region (a); with (b) exhibiting LGAs South and West of the Swan River and (c) LGAs North and East of the Swan River.

### Other considered data and approaches

In classifying the Landsat data a multitude of alternative approaches were attempted before arriving at one detailed within the main chapter. These included the use of different pre-processing data methodologies, classifiers and data combinations. Originally raw uncorrected (digital number) Landsat data was corrected using the Atmospheric Radiometric Calibration of Satellite Imagery (ARCSI) tool that makes use of the Py6S radiative transfer model (Bunting, 2017). However, due to the lack of availability of a number of required model parameters Landsat surface reflectance data was preferenced for consistency and repeatability. Numerous other classifiers and data combinations were tested including Support Vector Machines (SVMs) (Mountrakis et al., 2011), Multiple Endmember Analysis (MESMA) (Powell and Roberts, 2008), spectral indices such as the Normalised Difference Spectral Vector (NDSV) (Angiuli and Trianni, 2013) and classification of multi-temporal Landsat surface reflectance composites (Castrence et al., 2014). Nevertheless these were all found to produce unfavourable results in comparison to the presented approach or were unable to compute sub-pixel estimates (required within further chapters). Further information and discussion on these approaches is provided within section 2.2. 

In a similar theme alternative data sources were considered and tested for classification validation such as GlobeLand30 (Chen et al., 2015) and the European Space Agency’s (ESA) Climate Change Initiative (CCI) annual global land cover (300 m) time series (1992-2015) (European Space Agency, 2017). However, these products are constrained by limited temporal frequency (e.g. GlobeLand30), inadequate resolution (e.g. CCI), their own internal errors (e.g. based upon an accuracy assessment) and selection of global reference data that could fail to represent the land cover heterogeneity within the Perth Metropolitan Region. Consequently this prior work and reasoning guided the analysis undertaken in chapter 4.

### Chapter data list

This section provides an overview of the data presented and analysed within this chapter.

Supplementary Table 4 3. Summary of the data, sources and applications used within chapter 4.
Data	Source	Application
Annual population data	Australian Bureau of Statistics	Contextual information 
Annual natural resources value	The Government of Western Australia, Department of Mines and Petroleum annual reports	Contextual information
Landsat surface reflectance data, path 112 and 113, row 82
Dates and paths
1990: 14/04 (path 112), 7/05 (path 113)
2000: 23/08 (path 112), 1/10 (path 113)
2005: 12/07 (path 112), 19/07 (path 113)
2007: 6/10 (path 112), 9/07 (path 113)
2013: 22/10 (path 112), 13/10 (path 113)
2015: 9/08 (path 112), 17/09 (path 113)
Sensors
Landsat 5 TM: 1990, 2003, 2005, 2007
Landsat 7 ETM+: 2000
Landsat 8 OLI: 2013, 2015	United States Geological Survey Earth Explorer system	Land cover analysis 
High resolution data (read only)	Google Earth	Accuracy assessment 
Comparison urban estimates	Western Australian Planning Commission	Comparison to the Commission’s estimates  
Spatial boundary outlines 	Australian Bureau of Statistics	Comparison to the Commission’s estimates 

