# Urbanisation-induced land cover temperature dynamics for sustainable future urban heat island mitigation

## Abstract

Urban land cover is one of the fastest global growing land cover types which permanently alters land surface properties and atmospheric interactions, often initiating an urban heat island effect. Urbanisation comprises a number of land cover changes within metropolitan regions. However, these complexities have been somewhat neglected in temperature analysis studies of the urban heat island effect, whereby over-simplification ignores the heterogeneity of urban surfaces and associated land surface temperature dynamics. Accurate spatial information pertaining to these land cover change – temperature relationships across space is essential for policy integration regarding future sustainable city planning to mitigate urban heat impacts. Through a multi-sensor approach, this research disentangles the complex spatial heterogeneous variations between changes in land cover (Landsat data) and land surface temperature (MODIS data), to understand the urban heat island effect dynamics in greater detail for appropriate policy integration. The application area is the rapidly expanding Perth Metropolitan Region in Western Australia. Results indicate that land cover change from forest to urban is associated with the greatest annual daytime and nighttime temperature change of 0.40 °C and 0.88 °C respectively. Conversely, change from grassland to urban minimises temperature change at 0.16 °C and 0.77 °C for annual daytime and nighttime temperature respectively. These findings are important to consider for proposed developments of the city as such detail is not currently considered in the urban growth plans for the Perth Metropolitan Region. The novel intra-urban research approach presented can be applied to other global metropolitan regions to facilitate future transition towards sustainable cities, whereby urban heat impacts can be better managed through optimised land use planning, moving cities towards alignment with the 2030 sustainable development goals and the City Resilience Framework. 
