# Conclusion

Data informed governance is key to ensure the sustainable (re)development of our global cities in accommodating the predicted additional 2.5 billion urban dwellers by 2050. The lack of globally endorsed scientifically valid frameworks, consistent devolution of responsibilities, use of unrepresentative data alongside varied methodological approaches have the potential to misguide future (re)development decisions. The overall thesis aim of demonstrating the application of Earth Observation (EO) data in quantifying urban growth and its impact on the UHI in order to illustrate its potential for informing both global and metropolitan sustainable city development goals was achieved.  

The first part of the thesis aim (quantification of urban growth) was established from papers 1 and 2. Specifically, an applied EO methodology was demonstrated over the Perth Metropolitan Region (PMR), which was found to have increased 45% between 1990 and 2015, over 320 km2. In comparison the Western Australian Planning Commission (WAPC) underestimated overall urban area across the Perth Metropolitan Region (PMR). Nevertheless a comparison between the classified Landsat data and hardened high resolution data (to Landsat pixel area) established that pixels containing <50% urban land cover are largely dominated by vegetation according to the high resolution dataset, whilst Landsat largely identified these pixels as urban. Overestimation of urban area was reiterated when comparing Landsat sub-pixel estimates to the percentage of urban area per Landsat pixel derived from the high resolution classification. The range of bias values over differing development subset types indicated the inappropriateness of applying a single global model in adjusting Landsat estimates. Consequently application of spatially explicit models based on development type reduced moderate resolution urban area over (under) estimation by on an average 55.08% in comparison to the high spatial resolution data set decreasing the average overestimation from 11.86 km2 per subset to just 0.09 km2. 

The latter part of the thesis aim (quantifying the impact on urban growth on the UHI) was determined from papers 3 and 4. Land cover associated Land Surface Temperature (LST) change across the PMR indicated that conversion from grassland to bare earth was associated with the greatest overall annual daytime increase in temperature (0.44 °C), whilst conversion from forest to low urban albedo was associated with the greatest nighttime temperature change (0.88 °C) and greatest daytime change (0.40 °C) in conversion to a low urban albedo surface. More locally, through combining EO data and spatial models urban development in the form of a low density sprawl (e.g. lower building heights, less dense vegetation and sprawled layout) within the PMR was found to produce higher average annual temperatures of 0.54 °C (paved), 0.39 °C (grass) and 0.14 °C (buildings) compared to that of a high density urban development. An applied application of this methodology was demonstrated using a recently submitted redevelopment proposal. Optimisation of vegetation location was achieved, reducing maximum, mean and minimum average temperatures by 0.9 °C, 0.8 °C and 0.4 °C respectively, whilst maintaining design characteristics such as vegetation height and spacing. 

**Combined, this PhD research has demonstrated the use of EO data, spatial models and geographic techniques in addressing metropolitan sustainability concerns through overcoming current methodological limitations facilitating the basis for scientifically valid and policy applicable data-informed governance. **

